version: "3.9"
services:
  backend:
    image: backend-spring
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_PORT: 3306
      DATABASE_DB: ${MYSQL_DATABASE}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - ./data/db:/var/lib/mysql
